name: "web_app"
mode: "dev"
port: 8081
version: "v0.0.1"
machine_id: 1
start_time: "2000-05-09"
client_url: "*"

log:
  level: "info"
  filename: "./logs/web_app.log"
  max_size: 100
  max_age: 30
  max_backups: 7

mysql:
    host: "209.141.59.82"
    port: 3306
    user: "ser283004932404"
    password: "Mark1590"
    dbname: "ser283004932404"
    max_idle_conns: 20
    max_conns: 100

file:
  filemaxsize: 2048
  savedir: "./static/upload/"
  httpurl: "http://127.0.0.1:8081"
  httpdir: "/static"

switch:
  username: "gyop"
  passtoken: "E@2wYZ!Asa"

etcd:
  endpoints:
    - "https://akile.pawstickchief.com:2379"
  dial_timeout: 3000
  ca_cert: "conf/ssl/akile/fullchain.pem"
  cert_file: "conf/ssl/akile/cert.pem"
  key_file: "conf/ssl/akile/privkey.pem"
  server_name: "akile.pawstickchief.com"
  etcdname: "admin"
  password: "Mark1590"

WXWork:
  apitoken: "c2ae10dc-c831-4d08-a573-f1515caedc6b"