basePath: /
definitions:
  models.ClientSwitchInfo:
    properties:
      SwitchName:
        type: string
      SwitchPort:
        type: string
      Vlan:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      code:
        type: integer
      data:
        type: string
      msg:
        type: string
    type: object
  models.SelectSwitchMac:
    properties:
      changVlan:
        type: integer
      shortMac:
        type: string
      switchLevel:
        type: integer
    required:
    - switchLevel
    type: object
host: 192.168.8.84:8081
info:
  contact: {}
  description: 通过mac地址查询对应设备所处交换机端口和vlan信息
  title: 交换机查询设备端口
  version: "1.0"
paths:
  /selectswitch:
    post:
      consumes:
      - application/json
      description: 查询交换机端口
      parameters:
      - description: 查询交换机的参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.SelectSwitchMac'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.ClientSwitchInfo'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: 查询交换机端口
swagger: "2.0"
