name: "client"
mode: "dev"
port: 8080
version: "v0.0.1"
machine_id: 1
start_time: "2000-05-09"
clientip: "127.0.0.1"
workdir: "work"

log:
  level: "info"
  filename: "logs/client.log"
  max_size: 100
  max_age: 30
  max_backups: 7

server:
    ip: "192.168.0.138"
    port: 8081
    heartbeat: 5
    hostname: "client"
    download_api: "/download"
    upload_api: "/upload"

websocket:
  reconnect_attempts: 3       # 重试次数
  reconnect_delay: 60         # 每次失败后的延迟时间（秒）
  retry_after_failure: 3600   # 全部失败后的等待时间（秒）
  reconnect_interval: 10 #重连间隔
  max_total_reconnect_attempts: 10 #最大重连次数